const GET_SOLO_RANKS = 'GET_SOLO_RANKS';
const GET_DUO_RANKS = 'GET_DUO_RANKS';
const GET_QUEUE = 'GET_QUEUE';
const GET_TOURNAMENTS = 'GET_TOURNAMENTS';
const GET_TOURNAMENT = 'GET_TOURNAMENT';
const GET_TOURNAMENT_REGISTRATION_LIST = 'GET_TOURNAMENT_REGISTRATION_LIST';
const ADD_USER_TO_TOURNAMENT = 'ADD_USER_TO_TOURNAMENT';
const ADD_TO_QUEUE = 'ADD_TO_QUEUE';
const EXIT_FROM_QUEUE = 'EXIT_FROM_QUEUE';
const START = 'START';

module.exports = {
  GET_SOLO_RANKS,
  GET_DUO_RANKS,
  GET_QUEUE,
  GET_TOURNAMENTS,
  GET_TOURNAMENT,
  GET_TOURNAMENT_REGISTRATION_LIST,
  ADD_USER_TO_TOURNAMENT,
  ADD_TO_QUEUE,
  EXIT_FROM_QUEUE,
  START,
};
