export const GET_SOLO_RANKS = 'GET_SOLO_RANKS';
export const GET_DUO_RANKS = 'GET_DUO_RANKS';
export const GET_QUEUE = 'GET_QUEUE';
export const GET_TOURNAMENTS = 'GET_TOURNAMENTS';
export const GET_TOURNAMENT = 'GET_TOURNAMENT';
export const GET_TOURNAMENT_REGISTRATION_LIST = 'GET_TOURNAMENT_REGISTRATION_LIST';
export const ADD_USER_TO_TOURNAMENT = 'ADD_USER_TO_TOURNAMENT';
